### ISSUE TITLE
Style Categories

### ISSUE THREAD

**Issue by 00alis** [arduino/glossary-content#12]
Currently they are on the bottom right corner of the page
![screenshot 2016-07-12 17 01 17](https://cloud.githubusercontent.com/assets/6151328/16771840/45580652-4852-11e6-8d9b-3412f83b7654.png)

While they should be just like this, no link needed
![screenshot 2016-07-12 17 02 04](https://cloud.githubusercontent.com/assets/6151328/16771891/677d5822-4852-11e6-907f-4837e5581b3b.png)

**Comment by gmarchiarduino** [comment]
@00alis 
currently if you click on the opening section's capital letter you reach the related category page (for instance only the glossary items starting with 'A'): are those categories needed? Or we could just keep the main list?

**Comment by 00alis** [comment]
We don't need a category for each letter of the alphabet on the sidebar, what we really need is a search field instead.
<img width="871" alt="screenshot 2017-06-12 12 43 26" src="https://user-images.githubusercontent.com/6151328/27030493-bfad01d8-4f6c-11e7-9007-3610f61d426c.png">

**Comment by gmarchiarduino** [comment]
links to letter-categories removed, @smellai let me know when the search bar HTML is ready so I can style it

thanks
