### ISSUE TITLE
Read More links

### ISSUE THREAD

**Issue by gmarchiarduino** [arduino/glossary-content#19]
@00alis 
on Glossary mockups you can reach the single article pages by the 'Read More' links in the main list, but in this way if an item has no 'Read More' link (because its content is too short) you cannot reach its related page to click the 'Edit This Page' button: we could remove the 'Read More' links from list items, add ellipsis when needed (if descriptions are too long) and make all titles linking to the related single pages.

Is it ok? let me know what do you think

thanks

**Comment by 00alis** [comment]
I don't think we need to add a link to 'Edit'to every single entry of the glossary, there is a message on where to make edits on the sidebar and I think that is enough.
<img width="185" alt="screenshot 2017-06-12 09 42 38" src="https://user-images.githubusercontent.com/6151328/27023609-92cda316-4f53-11e7-8500-155ecf701212.png">

This sentence will take you to the repo with the correct language, then you can look for the specific entry on Github directly, I think this is enough.

Full pages description we con have the button linking to the specific page.
<img width="844" alt="screenshot 2017-06-12 10 06 48" src="https://user-images.githubusercontent.com/6151328/27024442-d6ce76b4-4f56-11e7-8e23-259b918ca43a.png">

**Comment by gmarchiarduino** [comment]
ok thank you

**Comment by gmarchiarduino** [comment]
fixed, to be pushed on prod
