### ISSUE TITLE
typo on website

### ISSUE THREAD

**Issue by dneise** [arduino/glossary-content#22]
Hello, there's a typo on:
<https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37>

![aaaa](https://user-images.githubusercontent.com/8200858/40355790-a6cab6ec-5db7-11e8-83fd-dc4adb380828.png)

I did not know where to open issues regarding the website .. maybe you could create a little dummy repo for this? 

Cheers ... keep up the awesome work

**Comment by smellai** [comment]
Thank you @dneise I fixed the typo :+1:
